// lib/mockWishes.js

export const generateMockWishes = () => [
  { id: "m1", name: "James Smith", title: "New Laptop for Coding", description: "I need a laptop to learn web development and build projects.", amount: 500, verified: true, image: "/sample1.jpg", location: "New York, USA", created_at: "2025-10-18T10:00:00Z", raised: 120 },
  { id: "m2", name: "Emily Johnson", title: "Guitar Lessons", description: "I want to take guitar lessons and start a small band.", amount: 200, verified: false, image: "/sample2.jpg", location: "Los Angeles, USA", created_at: "2025-10-17T14:30:00Z", raised: 40 },
  { id: "m3", name: "Michael Brown", title: "Charity Support", description: "Help me fund a small charity project in my neighborhood.", amount: 300, verified: true, image: "/sample3.jpg", location: "Chicago, USA", created_at: "2025-10-15T09:20:00Z", raised: 90 },
  { id: "m4", name: "Olivia Davis", title: "Medical Expenses", description: "I need assistance with medical bills for my family.", amount: 1000, verified: true, image: "/sample4.jpg", location: "Houston, USA", created_at: "2025-10-10T08:15:00Z", raised: 420 },
  { id: "m5", name: "William Miller", title: "Photography Gear", description: "I need a camera and lens to pursue photography professionally.", amount: 750, verified: false, image: "/sample5.jpg", location: "Miami, USA", created_at: "2025-10-12T16:00:00Z", raised: 85 },
  { id: "m6", name: "Sophia Wilson", title: "Art Supplies", description: "Help me buy art materials for my school project.", amount: 150, verified: true, image: "/sample6.jpg", location: "Atlanta, USA", created_at: "2025-10-14T11:40:00Z", raised: 60 },
  { id: "m7", name: "Alexander Moore", title: "Laptop Upgrade", description: "My old laptop can't run development software anymore.", amount: 600, verified: false, image: "/sample7.jpg", location: "Dallas, USA", created_at: "2025-10-16T13:50:00Z", raised: 30 },
  { id: "m8", name: "Isabella Taylor", title: "Music Production Software", description: "I want to create music but need proper software.", amount: 350, verified: true, image: "/sample8.jpg", location: "San Francisco, USA", created_at: "2025-10-13T15:25:00Z", raised: 200 },
  { id: "m9", name: "Ethan Anderson", title: "Basketball Gear", description: "I want to buy proper gear to practice basketball.", amount: 250, verified: false, image: "/sample9.jpg", location: "Seattle, USA", created_at: "2025-10-11T12:10:00Z", raised: 20 },
  { id: "m10", name: "Mia Thomas", title: "Scholarship Fund", description: "Help me pay for college tuition this semester.", amount: 1200, verified: true, image: "/sample10.jpg", location: "Boston, USA", created_at: "2025-10-09T10:45:00Z", raised: 480 },
  { id: "m11", name: "Daniel Jackson", title: "Bike for Commuting", description: "I need a bike to commute to work safely.", amount: 400, verified: true, image: "/sample11.jpg", location: "Philadelphia, USA", created_at: "2025-10-18T07:30:00Z", raised: 140 },
  { id: "m12", name: "Charlotte White", title: "Laptop Stand & Desk", description: "Help me create a proper home office setup.", amount: 200, verified: false, image: "/sample12.jpg", location: "Denver, USA", created_at: "2025-10-15T09:10:00Z", raised: 10 },
  { id: "m13", name: "Matthew Harris", title: "Coding Bootcamp", description: "I want to join a coding bootcamp to improve my skills.", amount: 1500, verified: true, image: "/sample13.jpg", location: "Austin, USA", created_at: "2025-10-17T17:00:00Z", raised: 350 },
  { id: "m14", name: "Amelia Martin", title: "Photography Workshop", description: "I want to attend a photography workshop this summer.", amount: 350, verified: false, image: "/sample14.jpg", location: "Portland, USA", created_at: "2025-10-16T12:50:00Z", raised: 50 },
  { id: "m15", name: "David Thompson", title: "Charity Run", description: "Fund my participation in a charity marathon.", amount: 100, verified: true, image: "/sample15.jpg", location: "Orlando, USA", created_at: "2025-10-14T08:20:00Z", raised: 100 },
  { id: "m16", name: "Grace Garcia", title: "Art Exhibition", description: "I want to showcase my artwork in a local gallery.", amount: 500, verified: true, image: "/sample16.jpg", location: "San Diego, USA", created_at: "2025-10-13T14:35:00Z", raised: 260 },
  { id: "m17", name: "Joseph Martinez", title: "Musical Instrument", description: "I need a keyboard to learn music composition.", amount: 400, verified: false, image: "/sample17.jpg", location: "Las Vegas, USA", created_at: "2025-10-12T10:50:00Z", raised: 75 },
  { id: "m18", name: "Abigail Robinson", title: "Cooking Classes", description: "I want to attend advanced cooking classes.", amount: 250, verified: true, image: "/sample18.jpg", location: "Phoenix, USA", created_at: "2025-10-11T09:05:00Z", raised: 35 },
  { id: "m19", name: "Christopher Clark", title: "Fitness Equipment", description: "I need a home gym setup to stay healthy.", amount: 600, verified: false, image: "/sample19.jpg", location: "Minneapolis, USA", created_at: "2025-10-10T11:15:00Z", raised: 10 },
  { id: "m20", name: "Elizabeth Rodriguez", title: "Laptop for School", description: "I need a new laptop for school assignments.", amount: 700, verified: true, image: "/sample20.jpg", location: "Charlotte, USA", created_at: "2025-10-09T13:25:00Z", raised: 600 },
];
